- name: Playbook name is 1st play
  hosts: all
  tasks:
      - name: Print Hello from task1 of play1
        ansible.builtin.debug:
               msg: Hai from task1 of play1


      - name: print the uptime on all the machine
        ansible.builtin.shell: "uptime"
               
  