- name: Demo on facts
  hosts: all
  tasks: 
      - name: print os distro
        ansible.builtin.debug:
              msg: OS Distro is {{ansible_distribution}}
      - name: Printing Mac Address 
        ansible.builtin.debug:
              msg: IP Address is {{ test_list | ansible.utils.ipaddr }}