- name: Demo on register
  hosts: all
  tasks:
    - name: Running a shell command
        ansible.builtin.shell: id
         register: OUT

    - name: Prinint the registered output
        ansible.builtin.debug:
          msg: "{{OUT.stdout}}"