- name: coping {{COMPONENT}} repo file
  ansible.builtin.copy:
     src: mysql.repo
     dest: /etc/yum.repos.d/mongodb.repo

- name: installing {{COMPONENT}}
  ansible.builtin.yum:
     name: 
       - mysql-community-server 
       - MySQL-python
     state: present

     
- name: Starting the {{COMPONENT}}  service
  ansible.builtin.service:
    name: mysqld
    state: started
    enabled: yes

- name: Check the {{COMPONENT}} password by fetching from the logs
  community.mysql.mysql_info:
    login_user: root
    login_password: RoboShop@1
  ignore_errors: yes
  register: mysql_stat

- name: Reset password
  when: mysql_stat.failed
  block:
    - name: Fetching  password
      ansible.builtin.shell: grep "temporary" /var/log/mysqld.log | head -n 1 | awk -F " " '{print $NF}'
      register: DEFAULT_ROOT_PASSWORD

    - name: Copy the sql password command file
      ansible.builtin.copy:
        src: rootpassword.sql
        dest: /tmp/rootpassword.sql
        
    - name: Changing   password
      ansible.builtin.shell: mysql --connect-expired-password -uroot -p"{{DEFAULT_ROOT_PASSWORD.stdout}}" < /tmp/rootpassword.sql

- name: Checking the validate_password plugin
  ansible.builtin.shell: echo show plugin | mysql -uroot -pRoboShop@1 | grep validate_password
  register: PLUGIN_INFO
  ignore_errors: yes 

- name: uninstalling the plugin
  when: PLUGIN_INFO.rc == 0
  block: 
    - name: copying the SQL password command file
      ansible.builtin.copy:
        src: password-validate.sql
        dest: /tmp/password-validate.sql 

    - name: Checking the validate_password plugin
      ansible.builtin.shell: mysql --connect-expired-password -uroot -p"{{DEFAULT_ROOT_PASSWORD.stdout}}" < /tmp/password-validate.sql






  
