- name: coping {{COMPONENT}} repo file
  ansible.builtin.copy:
     src: mysql.repo
     dest: /etc/yum.repos.d/mongodb.repo

- name: installing {{COMPONENT}}
  ansible.builtin.yum:
     name: mysql-community-server 
     state: present

     
- name: Starting the {{COMPONENT}}  service
  ansible.builtin.service:
    name: mysql
    state: started
    enabled: yes

- name: Check the {{COMPONENT}} password by fetching from the logs
  community.mysql.mysql_info:
    login_user: root
    login_password: RoboShop@1
   

  
