- name: configure the Yum repo
  ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash

- name: installing nodejs
  ansible.builtin.yum:
     name: "{{item}}"
     state: present
  loop:
    - nodejs
    - gcc-c++

- name: creating application user
  ansible.builtin.user:
    name: "{{APPUSER}}"
    comment: Roboshop Application user

- name: Cleanup of old html content
  ansible.builtin.file:
     path: /home/{{APPUSER}}/{{COMPONENT}}/
     state: absent

- name: Dawnloading {{COMPONENT}}
  ansible.builtin.unarchive:
     src: https://github.com/stans-robot-project/catalogue/archive/main.zip
     dest: /tmp
     remote_src: yes

-  name: coping {{COMPONENT}} to {{APPUSER}}
   ansible.builtin.copy:
     src: /tmp/{{COMPONENT}}-main/
     dest: /home/{{APPUSER}}/{{COMPONENT}}/
     remote_src: yes
     become_user: "{{APPUSER}}"
