- name: configure the Yum repo
  ansible.builtin.shell: curl --silent --location https://rpm.nodesource.com/setup_16.x | sudo bash -

- name: Install NodeJS 
  ansible.builtin.yum:
    name: "{{item}}"
    state: present  
  loop: 
    - nodejs 
    - gcc-c++ 

- name: creating application user
  ansible.builtin.user:
    name: "{{APPUSER}}"
    comment: Roboshop Application user

- name: Cleanup of old html content
  ansible.builtin.file:
     path: /home/{{APPUSER}}/{{COMPONENT}}/
     state: absent

- name: Dawnloading {{COMPONENT}}
  ansible.builtin.unarchive:
     src: https://github.com/stans-robot-project/catalogue/archive/main.zip
     dest: /tmp
     remote_src: yes

-  name: coping {{COMPONENT}} to {{APPUSER}}
   ansible.builtin.copy:
     src: /tmp/{{COMPONENT}}-main/
     dest: /home/{{APPUSER}}/{{COMPONENT}}/
     remote_src: yes
     become_user: "{{APPUSER}}"

- name: Install NodeJS  packages based on package.json file 
  community.general.npm:
     path: /home/{{APPUSER}}/{{COMPONENT}}/


-  name: coping systemd file
   ansible.builtin.copy:
     src: systemd.service
     dest: /etc/systemd/system/catalogue.service

- name: Starting the {{COMPONENT}} service
  ansible.builtin.systemd:
    name: "{{COMPONENT}}"
    state: restarted
    enabled: yes
    daemon_reload: yes

  
    
     
